// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whzan_API.EF.Context;

#nullable disable

namespace Whzan_API.Migrations
{
    [DbContext(typeof(WhzanCatalogDBContext))]
    [Migration("20251130191611_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Whzan_API.EF.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "$",
                            Name = "US Dollar"
                        },
                        new
                        {
                            Id = 2,
                            Code = "R",
                            Name = "Rand"
                        });
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Favourite");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://media.takealot.com/covers_images/ada2654a1b6f49e298336ac8e5e4d156/s-zoom.file"
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://media.takealot.com/covers_images/d6849ec5f50a409aa6306255409957e3/s-zoom.file"
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://media.takealot.com/covers_images/52fc46b0248f471db459838937999eb3/s-zoom.file"
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://media.takealot.com/covers_images/3d3c187f5fef403e88a32d56f7e0647e/s-zoom.file"
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://media.takealot.com/covers_images/ff210e16d57f48c698034c35a8dee348/s-zoom.file"
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://media.takealot.com/covers_images/2827a86a69744e36a60a375b573e9be3/s-zoom.file"
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://media.takealot.com/covers_images/599c45b09a8b41df82d0f28a8cbddc5c/s-zoom.file"
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://media.takealot.com/covers_images/2e1d4ba85c1c4a69b31454ec03a464b8/s-zoom.file"
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://media.takealot.com/covers_images/0241de942b2a431c8d326f9a4ffdbb9a/s-zoom.file"
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://media.takealot.com/covers_images/f12610962a184b00a96870ca42f36507/s-zoom.file"
                        },
                        new
                        {
                            Id = 11,
                            ImageURL = "https://media.takealot.com/covers_images/434e43a10f504d30b44d5b1f23c32b07/s-zoom.file"
                        },
                        new
                        {
                            Id = 12,
                            ImageURL = "https://media.takealot.com/covers_images/cbab723c5d404752866fe30f8a5fbb36/s-zoom.file"
                        },
                        new
                        {
                            Id = 13,
                            ImageURL = "https://media.takealot.com/covers_images/68e38c6ded394787985de7f9583b408c/s-zoom.file"
                        },
                        new
                        {
                            Id = 14,
                            ImageURL = "https://media.takealot.com/covers_images/1314ce11ae994990bac2320c1ee607a9/s-zoom.file"
                        },
                        new
                        {
                            Id = 15,
                            ImageURL = "https://media.takealot.com/covers_images/5af2807dd6f84bdb88a30f647d083a6e/s-zoom.file"
                        },
                        new
                        {
                            Id = 16,
                            ImageURL = "https://media.takealot.com/covers_images/cd58f55bbb4b448f99e99fbcb555493c/s-zoom.file"
                        },
                        new
                        {
                            Id = 17,
                            ImageURL = "https://media.takealot.com/covers_images/dddd25a12747493eb8353b10c71576a7/s-zoom.file"
                        },
                        new
                        {
                            Id = 18,
                            ImageURL = "https://media.takealot.com/covers_images/61625c49992241acb65b9191e21de793/s-zoom.file"
                        },
                        new
                        {
                            Id = 19,
                            ImageURL = "https://media.takealot.com/covers_images/0c1c1ae3580148529088079267e18f8e/s-zoom.file"
                        },
                        new
                        {
                            Id = 20,
                            ImageURL = "https://media.takealot.com/covers_images/7e0a4b3692cb4895b45432e89e22f978/s-zoom.file"
                        },
                        new
                        {
                            Id = 21,
                            ImageURL = "https://media.takealot.com/covers_images/7a9d16396be5483e9a1f3bfdc5d23ecf/s-zoom.file"
                        },
                        new
                        {
                            Id = 22,
                            ImageURL = "https://media.takealot.com/covers_images/f66e2b0c7aa64e3ea18055c5d44580fb/s-zoom.file"
                        },
                        new
                        {
                            Id = 23,
                            ImageURL = "https://media.takealot.com/covers_images/072823ead7a24449aed85592e2fec96f/s-zoom.file"
                        },
                        new
                        {
                            Id = 24,
                            ImageURL = "https://media.takealot.com/covers_images/dd9e2c8f33034aefb5ae921f9adb592c/s-zoom.file"
                        },
                        new
                        {
                            Id = 25,
                            ImageURL = "https://media.takealot.com/covers_images/825e3017cbb84c779176fc5af7f5471d/s-zoom.file"
                        },
                        new
                        {
                            Id = 26,
                            ImageURL = "https://media.takealot.com/covers_images/e689bb5a45994ffa832cce32fddf2a67/s-zoom.file"
                        },
                        new
                        {
                            Id = 27,
                            ImageURL = "https://media.takealot.com/covers_images/a35456fce4034864a82bce57674d171a/s-zoom.file"
                        },
                        new
                        {
                            Id = 28,
                            ImageURL = "https://media.takealot.com/covers_images/a8734d0db2554a6381e5e31a4e11a2cc/s-zoom.file"
                        },
                        new
                        {
                            Id = 29,
                            ImageURL = "https://media.takealot.com/covers_images/b4359d3c59c042e5a6e52aa44e8e4575/s-zoom.file"
                        },
                        new
                        {
                            Id = 30,
                            ImageURL = "https://media.takealot.com/covers_images/5eb9ca39bcae47e591157b989d70927e/s-zoom.file"
                        },
                        new
                        {
                            Id = 31,
                            ImageURL = "https://media.takealot.com/covers_images/6c861aed47a34d549f7f17b0d81c4fd3/s-zoom.file"
                        },
                        new
                        {
                            Id = 32,
                            ImageURL = "https://media.takealot.com/covers_images/fc1000768be64c64b3a57ffdd0691b35/s-zoom.file"
                        });
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isWatched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "JBL",
                            Currency = "Rands",
                            Description = "JBL Live 770NC headphones deliver powerful JBL Signature Sound in a comfortable over-ear headband style.",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "JBL Live 770NC Wireless Bluetooth Over-Ear Noise Cancelling Headphones",
                            Price = 1925m,
                            Rating = 4.3m,
                            ReviewCount = 103,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Timex",
                            Currency = "Rands",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "Timex Expedition Gallatin Solar-Powered (TW4B14500)",
                            Price = 2399m,
                            Rating = 3.8m,
                            ReviewCount = 25,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Soundcore",
                            Currency = "Rands",
                            Description = "98.5% Noise Reduction. Adaptive Noise Cancelling. Hi-Res Sound. 50H Battery. Wireless Charging. Bluetooth 5.3",
                            InStock = false,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "Soundcore by Anker Liberty 4 NC Wireless Noise Cancelling Earbuds",
                            Price = 1299m,
                            Rating = 4.5m,
                            ReviewCount = 32,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Beyerdynamic",
                            Currency = "Rands",
                            Description = "Beyerdynamic AVENTHO 100 features more than 60 hours playtime & up to 40 hours with ANC.",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "Beyerdynamic AVENTHO 100 Wireless On-Ear Headphones With ANC - Cream",
                            Price = 4499m,
                            Rating = 4.1m,
                            ReviewCount = 77,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 5,
                            Brand = "JBL",
                            Currency = "Rands",
                            Description = "JBL Pro Sound, Dynamic Lightshow, 15H Playtime, Auracast Multi-Speaker Connection & Splashproof",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "JBL PartyBox On-The-Go 2 Portable Bluetooth Party Speaker with Wireless Mic",
                            Price = 5999m,
                            Rating = 4.2m,
                            ReviewCount = 61,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Hisense",
                            Currency = "Rands",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "Hisense 65inch E7Q 4K UHD QLED Smart TV with Dolby Vision",
                            Price = 7999m,
                            Rating = 4.8m,
                            ReviewCount = 22,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Huawei",
                            Currency = "Rands",
                            Description = "3-Hour Listening on 10-minute Charge | Long Press to Pair| Bluetooth5.4 Connect | IP54 Dust &Splash-Resistance",
                            InStock = false,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "HUAWEI FreeBuds SE 3 -Earphones/Wireless Earbuds|42-Hour Battery Life-Black",
                            Price = 999m,
                            Rating = 4.5m,
                            ReviewCount = 87,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Sennheiser",
                            Currency = "Rands",
                            Description = "Wireless Over-Ear Noise Cancelling Headphones",
                            InStock = true,
                            IsFavourite = false,
                            IsPredefined = true,
                            Name = "Sennheiser MOMENTUM 4 Wireless Over-Ear Noise Cancelling Headphones (Teal)",
                            Price = 5450m,
                            Rating = 3.5m,
                            ReviewCount = 50,
                            UpdatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            isWatched = false
                        });
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCurrency");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageId = 11,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageId = 12,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageId = 13,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageId = 14,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImageId = 15,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImageId = 16,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageId = 17,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageId = 18,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImageId = 19,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImageId = 20,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImageId = 21,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImageId = 22,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 23,
                            ImageId = 23,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImageId = 24,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            ImageId = 25,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageId = 26,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            ImageId = 27,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 28,
                            ImageId = 28,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            ImageId = 29,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImageId = 30,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 31,
                            ImageId = 31,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 32,
                            ImageId = 32,
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Watched", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Watched");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Favourite", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithOne("Favourite")
                        .HasForeignKey("Whzan_API.EF.Models.Favourite", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductCategory", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductCurrency", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Currency", "Currency")
                        .WithMany("ProductCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithMany("ProductCurrencies")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductImage", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Image", "Image")
                        .WithMany("ProductImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.ProductTag", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whzan_API.EF.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Watched", b =>
                {
                    b.HasOne("Whzan_API.EF.Models.Product", "Product")
                        .WithOne("WatchedProduct")
                        .HasForeignKey("Whzan_API.EF.Models.Watched", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Currency", b =>
                {
                    b.Navigation("ProductCurrencies");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Image", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Product", b =>
                {
                    b.Navigation("Favourite");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductCurrencies");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductTags");

                    b.Navigation("WatchedProduct");
                });

            modelBuilder.Entity("Whzan_API.EF.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
